version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cardpooling
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/cardpooling
    ports:
      - "8000:8000"
    volumes:
      - ./backend/apps:/app/apps
    
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"


volumes:
  pgdata: