FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY apps backend/apps

# Change this line: it should match your FastAPI entrypoint
CMD ["uvicorn", "backend.apps.app:app", "--host", "0.0.0.0", "--port", "8000"]